  spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: menu
          contentType: application/json
        greetings-out:
          destination: menu
          contentType: application/json